version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: release/dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-development:
        dependency-type: development
      npm-runtime:
        dependency-type: production
  - package-ecosystem: github-actions
    directory: /
    target-branch: release/dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
